name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install build system
      run: |
        sudo apt-get update
        sudo apt-get install cmake pkg-config
      
    - name: Install gcc
      run: sudo apt-get install gcc-13 g++-13
    
    - name: Install OpenGL
      run: |
        sudo apt-get update
        sudo apt-get install cmake pkg-config
        sudo apt-get install mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev
        sudo apt-get install libglew-dev libglfw3-dev libglm-dev
        sudo apt-get install libao-dev libmpg123-dev
    
    - name: Install UDev
      run: sudo apt-get install -y libudev-dev
        
    - name: Install OpenAL
      run: sudo apt-get install libopenal-dev
      
    - name: Install Vorbis
      run: |
        sudo apt-get install libvorbis-dev
        sudo apt-get -y install libvorbisenc2
        sudo apt-get -y install libvorbisfile3
        
    - name: Install Flac
      run: sudo apt-get install libflac-dev
      
    - name: Install XCursor
      run: sudo apt install libxcursor-dev
    
    # - uses: openrndr/setup-opengl@v1.1

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=g++-13

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --output-on-failure

